# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fc897060dc1764ede43c17eafa33754"
name = "hour-keeper"
application_url = "https://wrong-reserved-caused-zum.trycloudflare.com"
embedded = true
handle = "hour-keeper"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://wrong-reserved-caused-zum.trycloudflare.com/auth/callback", "https://wrong-reserved-caused-zum.trycloudflare.com/auth/shopify/callback", "https://wrong-reserved-caused-zum.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
